[package]
name = "number_theoretic_transform"
version = "0.1.0"
edition = "2024"

[dependencies]
primal = "0.3"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "my_benchmark"
harness = false